CREATE SEQUENCE tbl_usuario_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE tbl_usuario(
    USUARIO_ID NUMBER DEFAULT tbl_usuario_seq.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(20) NOT NULL
);