CREATE SEQUENCE tbl_alimento_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_ALIMENTO (
    ALIMENTO_ID INTEGER DEFAULT tbl_alimento_seq.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    PORCAO VARCHAR2(30) NOT NULL,
    QTDE_PROTEINA NUMBER(9,3) NOT NULL,
    QTDE_CARBOIDRATO NUMBER(9,3) NOT NULL,
    QTDE_GORDURAS NUMBER(9,3) NOT NULL,
    TOTAL_CALORIAS NUMBER(9,3) NOT NULL
);